project_id = "qewuorfsbdcakfraxlev"

[functions.send-task-notification]
verify_jwt = true

[functions.send-assignment-notification]
verify_jwt = true

[functions.send-project-member-notification]
verify_jwt = true

[functions.create-notification]
verify_jwt = true

[functions.admin-create-user]
verify_jwt = true

[functions.admin-reset-password]
verify_jwt = true
